import type { Config } from 'tailwindcss';

const config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        primary: {
          0: '#FFF5F6',
          1: '#FFEBEE',
          2: '#FFCCD3',
          3: '#FF99A8',
          4: '#FF3351',
          5: '#FF0025',
          6: '#E50021',
          7: '#C2001C',
          8: '#940015',
          9: '#66000F',
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          0: '#FCFDFD',
          1: '#F9F9FA',
          2: '#F1F1F4',
          3: '#DFE2E7',
          4: '#B3BAC6',
          5: '#8C99AC',
          6: '#334867',
          7: '#001A41',
          8: '#000E2E',
          9: '#00071F',
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        valid: {
          0: '#F2FDF4',
          1: '#EDFCF0',
          2: '#9AEEAB',
          3: '#0FD277',
          4: '#00B86B',
          5: '#008E53',
          6: '#007545',
          7: '#005C36',
          8: '#004227',
          9: '#00331E',
        },
        info: {
          0: '#F7FCFF',
          1: '#E9F6FF',
          2: '#94CFF6',
          3: '#5CA8E6',
          4: '#3381CE',
          5: '#0050AE',
          6: '#003D95',
          7: '#002D7D',
          8: '#002064',
          9: '#001653',
        },
        warning: {
          0: '#FEFBF1',
          1: '#FEF3D4',
          2: '#FEE5AA',
          3: '#FED27F',
          4: '#FDC05F',
          5: '#FDA22B',
          6: '#D9801F',
          7: '#B66215',
          8: '#92470D',
          9: '#793408',
        },
        error: {
          0: '#FEEFEB',
          1: '#FDDDD4',
          2: '#FBB5A9',
          3: '#F4837D',
          4: '#E95B61',
          5: '#DB2941',
          6: '#BC1D42',
          7: '#9D1440',
          8: '#7F0D3C',
          9: '#690739',
        },
        neutral: {
          0: '#FFFFFF',
          1: '#FAFAFB',
          2: '#E9E8ED',
          3: '#CCCFD3',
          4: '#99A0A7',
          5: '#66707a0f',
          6: '#4E5764',
          7: '#F6F3F3',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  // eslint-disable-next-line global-require
  plugins: [require('tailwindcss-animate')],
} satisfies Config;

export default config;
